### ISSUE TITLE
V1.2 User stories

### ISSUE THREAD

**Issue by sophiien** [AY2122S2-CS2103-W16-1/tp#3]
1. As a university student, I would like to be able to find information regarding the module from the professors teaching the module beforehand so that I can make a more informed decision when it comes to choosing my module. 
2. As a university student, I would like to be able to know where to find the relevant channels to seek help from professors and fellow classmates so that I can clarify any questions I have about the course. 
3. As a university student, I would like to know where and when are my professors' office hours such that I can find them for arrange for consultation sessions. 
4. As a university student, I would like to be able to have a one stop platform for easy access to any module's information so that I need not waste time looking for these information.

**Comment by ryanwalterlee** [comment]
1. As a uni student, I would want something that can help me keep track of the professors contacts, so that I can retrieve it easily to communicate with the professors.
2. As a uni student, I would want something that can help me keep track of the module mates contacts, so that I can easily find others to discuss module content with.
3. As a uni student, I would want to easily and quickly retrieve contacts of students and professors so that I can save time.
4. As a uni student, I would want a platform that can store many types of contacts such as email, telegram, phone number incase I cannot reach someone through one communication platform.
